<!-- YAML
added: v0.9.4
-->

* {Error}


`'error'` 事件可能随时由 `Readable` 实现触发。 
通常，如果底层的流由于底层内部的故障而无法生成数据，或者流的实现尝试推送无效的数据块，则可能会发生这种情况。

监听器回调将会传入一个 `Error` 对象。

