

* 继承自: {errors.Error}

表明断言的失败。 
详见 [`assert.AssertionError` 类][`Class: assert.AssertionError`]。

